name: Build and Release Rust Binary

permissions:
  contents: "write"

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - "completed"

jobs:
  tests:
    name: Tests if it can build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: renvsubst
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
