name: Build and Release Rust Binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo build --verbose

    - name: Run tests
      run: cargo test

    - name: Build for x86
      run: |
        rustup target add x86_64-unknown-linux-gnu
        cargo build --release --target=x86_64-unknown-linux-gnu

    - name: Build for Darwin
      run: |
        rustup target add x86_64-apple-darwin
        cargo build --release --target=x86_64-apple-darwin

    - name: Generate checksum for x86 binary
      run: sha256sum target/x86_64-unknown-linux-gnu/release/renvsubst_${{ env.GITHUB_REF }} > target/x86_64-unknown-linux-gnu/release/renvsubst_${{ env.GITHUB_REF }}.sha256

    - name: Generate checksum for Darwin binary
      run: sha256sum target/x86_64-apple-darwin/release/renvsubst_${{ env.GITHUB_REF }} > target/x86_64-apple-darwin/release/renvsubst_${{ env.GITHUB_REF }}.sha256

    - name: Upload darwin binary and its checksum as release assets
      uses: actions/upload-artifact@v2
      with:
        name: darwin
        path: |
          target/x86_64-apple-darwin/release/renvsubst_${{ env.GITHUB_REF }}
          target/x86_64-apple-darwin/release/renvsubst_${{ env.GITHUB_REF }}.sha256

    - name: Upload x86 binary and its checksum as release assets
      uses: actions/upload-artifact@v2
      with:
        name: x86
        path: |
          target/x86_64-unknown-linux-gnu/release/renvsubst_${{ env.GITHUB_REF }}
          target/x86_64-unknown-linux-gnu/release/renvsubst_${{ env.GITHUB_REF }}.sha256
