name: Build and Release Rust Code
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install macOS target
        run: rustup target add x86_64-apple-darwin
      - name: Install GNU target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Build for Linux (GNU)
        run: cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Build for Linux (musl)
        uses: ekidd/rust-musl-builder:latest
        with:
          build: cargo build --release
          target: x86_64-unknown-linux-musl
      - name: Build for macOS
        run: cargo build --release --target=x86_64-apple-darwin
      - name: Run tests
        run: cargo test --verbose
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false
      - name: Upload Linux Binary (GNU)
        uses: actions/upload-artifact@v2
        with:
          name: renvsubst-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/renvsubst
      - name: Upload Linux Binary (musl)
        uses: actions/upload-artifact@v2
        with:
          name: renvsubst-linux-musl
          path: target/x86_64-unknown-linux-musl/release/renvsubst
      - name: Upload macOS Binary
        uses: actions/upload-artifact@v2
        with:
          name: renvsubst-macos
          path: target/x86_64-apple-darwin/release/renvsubst
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: |
            ghcr.io/containeroo/renvsubst:${{ github.ref }}
            ghcr.io/containeroo/renvsubst:latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
