name: Release

on:
  push:
    tags:
      - "*"


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install cargo-release-action
        uses: cargo-release/cargo-release-action@v1.4.1
      - name: Build and Publish Docker Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo release --skip-publish --skip-tag --no-confirm --docker-build
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
